name: Bug Report
description: Signalez un bug
title: "[BUG]: "
labels: ["Nouveau"]
projects: ["Nexalia/5"]
body:
  - type: markdown
    attributes:
      value: |
        Tout bug par pport a Nexalia doit être signalé ici.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Quel est la description du bug
      placeholder: Quand on dit bonjour dans le chat le monde explose
    validations:
      required: true
  - type: dropdown
    id: priorite
    attributes:
      label: Priorité
      description: Quel est la dangereusité du bug
      options:
        - Extrême
        - Haute
        - Moyenne
        - Basse
        - Nulle
      default: 3
    validations:
      required: true
  - type: textarea
    id: resolution
    attributes:
      label: Résolution
      description: Comment pensez vous régler le bug?
      placeholder: En supprimant la fonctionnalité
    validations:
      required: true      
